# src/aee/ingestion/cleaning.py

import re
from typing import Dict

class TextCleaner:
    """
    Utility class for post-processing and cleaning text extracted from PDFs.
    Focuses on fixing common OCR/parsing artifacts in scientific literature.
    """

    # Ligature mappings
    _LIGATURES: Dict[str, str] = {
        "ﬂ": "fl", "ﬁ": "fi", "ﬀ": "ff",
        "ﬃ": "ffi", "ﬄ": "ffl"
    }

    # Common scientific terms often broken by PDF parsing (e.g., "p H" -> "pH")
    _SCIENTIFIC_FIXES: Dict[str, str] = {
        "p H": "pH",
        "K m": "Km",
        "V max": "Vmax",
        "C min": "Cmin",
        "C max": "Cmax",
        "et al .": "et al.",
    }

    # Pre-compiled regex patterns
    # Matches: [ 12, 13 ] -> [12, 13]
    _CITATION_RE = re.compile(r'\[\s+(\d+(?:,\s*\d+)*)\s+\]')
    
    # Matches: Fe 3 O 4 -> Fe3O4 (Letter-Space-Digit and Digit-Space-Letter)
    _CHEM_LSD_RE = re.compile(r'([a-zA-Z])\s+(\d)')
    _CHEM_DSL_RE = re.compile(r'(\d)\s+([a-zA-Z])')

    @classmethod
    def clean_docling_markdown(cls, text: str) -> str:
        """
        Cleans markdown text generated by Docling.

        Applies the following fixes:
        1. Normalizes unicode ligatures.
        2. Reconstructs broken scientific terms (pH, Km).
        3. Removes spaces in chemical formulas (Fe 3 -> Fe3).
        4. Fixes citation formatting.

        Args:
            text: Raw markdown text.

        Returns:
            Cleaned text string.
        """
        if not text:
            return ""

        # 1. Fix ligatures
        for lig, sub in cls._LIGATURES.items():
            if lig in text:
                text = text.replace(lig, sub)

        # 2. Fix specific broken scientific terms
        for broken, fixed in cls._SCIENTIFIC_FIXES.items():
            if broken in text:
                text = text.replace(broken, fixed)

        # 3. Fix chemical formulas (remove spaces between letters and numbers)
        # Run twice to handle chains like C 6 H 12
        text = cls._CHEM_LSD_RE.sub(r'\1\2', text)
        text = cls._CHEM_DSL_RE.sub(r'\1\2', text)

        # 4. Fix citation spacing
        text = cls._CITATION_RE.sub(r'[\1]', text)

        return text