name: nanozymes
fields:
  activity:
    type: str
    description: >-
      Тип ферментоподобной каталитической активности (например, пероксидазная, каталазная,
      оксидазная), которую имитирует исследуемый наноматериал (нанозим).
    required: false
  ccat_unit:
    type: str
    description: >-
      Единица измерения физической величины (массы, массовой или молярной концентрации),
      описывающая количественное содержание основного катализатора (нанозима) в реакционной
      системе при проведении кинетических испытаний.
    required: false
  ccat_value:
    type: str
    description: >-
      Абсолютная практическая масса или концентрация катализатора (нанозима), внесенного
      в реакционную систему для проведения стационарных кинетических измерений. Атрибут
      детерминирует макроскопическое количество всего синтезированного композитного
      материала, выступающего в роли катализатора, и является фундаментальным параметром
      внешней среды эксперимента.
    required: false
  c_const:
    type: str
    description: >-
      Фиксированная (постоянная) молярная концентрация ко-субстрата в финальной реакционной
      смеси при проведении стационарных кинетических измерений (определении параметров
      Михаэлиса-Ментен), выступающая фоновым условием при варьировании концентрации
      основного исследуемого субстрата.
    required: false
  c_const_unit:
    type: str
    description: >-
      Единица измерения фиксированной (постоянной) молярной концентрации ко-субстрата
      (например, H2O2 или TMB) в реакционной смеси при проведении кинетических испытаний.
      Обозначает размерность величины, которая остается неизменной, пока концентрация
      другого субстрата варьируется.
    required: false
  c_max:
    type: str
    description: >-
      Точное числовое значение максимальной концентрации варьируемого субстрата (например,
      H2O2, TMB), применяемой в серии кинетических экспериментов для расчета параметров
      ферментативной активности (по модели Михаэлиса-Ментен). Значение представляет
      собой верхний предел исследованного концентрационного диапазона или максимальный
      элемент массива заданных концентраций, строго нормализованный к единице измерения
      миллимоль на литр (мМ).
    required: false
  c_max_unit:
    type: str
    description: >-
      Единица измерения максимальной (или граничной) концентрации субстрата, используемой
      в кинетических экспериментах. Отражает физическую размерность верхнего предела
      тестируемого диапазона или максимального значения из массива концентраций.
    required: false
  c_min:
    type: str
    description: Минимальная концентрация варьируемого субстрата в кинетическом эксперименте.
    required: false
  c_min_unit:
    type: str
    description: >-
      Физическая единица измерения минимальной концентрации целевого субстрата в реакционной
      смеси, используемая для построения кинетических кривых и расчета каталитических
      параметров. Абсолютный инвариант: размерность молярной концентрации.
    required: false
  depth:
    type: str
    description: >-
      Третий пространственный (линейный) размер первичной целевой наночастицы как
      единого физического макрообъекта (глубина/толщина). Для изотропных частиц (сферические,
      кубические) геометрически эквивалентен их диаметру или общему размеру (size).
      Для анизотропных частиц (например, наностержней) эквивалентен ширине (width)
      поперечного сечения. Описывает физические габариты сухого ядра частицы (по данным
      электронной микроскопии).
    required: false
  depth_unit:
    type: str
    description: >-
      Единица измерения пространственной протяженности (глубины/толщины) целевой наноструктуры.
      В контексте изотропных (сферических) или комплексных частиц семантически и синтаксически
      эквивалентна единице измерения общего размера, диаметра или ширины, характеризующей
      физические габариты исследуемого объекта.
    required: false
  formula:
    type: str
    description: >-
      Стандартизированная базовая химическая формула или общепринятая структурная
      аббревиатура (например, MMT) целевого каталитически активного наноматериала
      (нанозима). Описывает фундаментальный макро-состав объекта, полностью абстрагируясь
      от его физической морфологии, структурных эпитетов и функциональных ролей в
      тексте.
    required: false
  km_unit:
    type: str
    description: >-
      Единица измерения константы Михаэлиса (Km). Обозначает размерность концентрации
      субстрата, при которой скорость каталитической (ферментативной или псевдоферментативной)
      реакции достигает половины от максимальной (Vmax).
    required: false
  km_value:
    type: str
    description: >-
      Числовое значение константы Михаэлиса (Km), отражающее сродство катализатора
      (фермента или нанозима) к конкретному субстрату. Представляет собой концентрацию
      субстрата, при которой скорость каталитической реакции достигает половины от
      максимальной (Vmax).
    required: false
  length:
    type: str
    description: >-
      Физический линейный размер (диаметр, длина или усредненный габарит) первичной
      целевой наночастицы как единого целого (твердого ядра), обычно определяемый
      методами электронной микроскопии (TEM, SEM).
    required: false
  length_unit:
    type: str
    description: >-
      Строгая метрическая единица измерения (например, нанометры - nm), используемая
      для количественного выражения линейных геометрических параметров (диаметра,
      длины, ширины, среднего размера) целевой наночастицы или исследуемой макро-системы.
    required: false
  ph:
    type: str
    description: >-
      Точное значение водородного показателя (pH) внешней реакционной среды (буферного
      раствора), зафиксированное для проведения стационарных кинетических измерений
      (steady-state kinetic assays) или утвержденное как оптимальное для целевой каталитической
      реакции.
    required: false
  reaction_type:
    type: str
    description: >-
      Тип каталитической реакции, строго определяемый комбинацией участвующих субстратов
      и ко-субстратов (например, донора электронов и окислителя), стандартизированный
      в виде формулы их совместного присутствия в реакционной среде.
    required: false
  surface:
    type: str
    description: >-
      Целенаправленно используемое химическое соединение, полимер или биологическая
      макромолекула, формирующая внешнее покрытие (оболочку), стабилизирующий слой
      или матрицу для синтеза индивидуальной наночастицы. Выступает в роли поверхностного
      модификатора, который предотвращает агломерацию и определяет физико-химические
      свойства границы раздела фаз нанозима.
    required: false
  syngony:
    type: str
    description: >-
      Фундаментальная геометрическая симметрия кристаллической решетки (базовая сингония)
      целевого наноматериала или его изолированных фаз, определяющая макроскопическую
      пространственную организацию атомов.
    required: false
  temperature:
    type: str
    description: >-
      Точное числовое значение температуры (в градусах Цельсия), при которой проводились
      основные кинетические или каталитические измерения.
    required: false
  vmax_unit:
    type: str
    description: >-
      Физическая единица измерения максимальной скорости каталитической или ферментативной
      реакции (Vmax), отражающая изменение концентрации вещества (субстрата или продукта)
      в единицу времени.
    required: false
  vmax_value:
    type: str
    description: >-
      Максимальная скорость ферментативной или каталитической реакции (Vmax). Количественная
      кинетическая характеристика, отражающая предельную скорость образования продукта
      (или расходования субстрата) каталитической системой при условии полного насыщения
      катализатора субстратом.
    required: false
  width:
    type: str
    description: >-
      Поперечный линейный размер (ширина) первичной наночастицы. Для изотропных морфологий
      (сферические, кубические частицы) ширина геометрически эквивалентна диаметру
      или базовому 'размеру' (size). Для анизотропных структур (наностержни, наноленты)
      ширина представляет собой поперечное измерение, перпендикулярное длине. Характеризует
      физические габариты твердого неорганического ядра.
    required: false
  width_unit:
    type: str
    description: >-
      Единица измерения поперечного линейного размера (ширины, диаметра или эквивалентного
      габарита) исследуемой наночастицы или её структурного компонента.
    required: false
compare_fields:
- activity
- ccat_unit
- ccat_value
- c_const
- c_const_unit
- c_max
- c_max_unit
- c_min
- c_min_unit
- depth
- depth_unit
- formula
- km_unit
- km_value
- length
- length_unit
- ph
- reaction_type
- surface
- syngony
- temperature
- vmax_unit
- vmax_value
- width
- width_unit
float_tolerance: 0.05
