# Task Schema Configuration for Nanozyme Extraction
# This schema defines the structure, types, constraints, and evaluation fields
# for the data extracted from scientific articles.

name: "nanozymes"

fields:
  formula:
    type: "str"
    description: "Formula"
    required: true

  activity:
    type: "str"
    description: "Activity"
    required: true
    choices: ["peroxidase", "oxidase", "catalase", "laccase", "glucose", "glucose oxidase"]

  syngony:
    type: "str"
    description: "Syngony"
    choices: ["cubic", "hexagonal", "tetragonal", "monoclinic", "orthorhombic", "trigonal", "triclinic", "amorphous", "rhombohedral", "0"]
    required: false

  length:
    type: "str"
    description: "Length"
    required: false
  length_unit:
    type: "str"
    description: "Length Unit"
    required: false

  width:
    type: "str"
    description: "Width"
    required: false
  width_unit:
    type: "str"
    description: "Width unit"
    required: false

  depth:
    type: "str"
    description: "Depth"
    required: false
  depth_unit:
    type: "str"
    description: "Depth unit"
    required: false

  surface:
    type: "str"
    description: "Surface"
    required: false

  km_value:
    type: "str"
    description: "Km value"
    required: false
  km_unit:
    type: "str"
    description: "Km unit"
    required: false

  vmax_value:
    type: "str"
    description: "Vmax value"
    required: false
  vmax_unit:
    type: "str"
    description: "Vmax unit"
    required: false

  reaction_type:
    type: "str"
    description: "Reaction type"
    required: false

  c_min:
    type: "str"
    description: "C min"
    required: false
  c_min_unit:
    type: "str"
    description: "C min unit"
    required: false

  c_max:
    type: "str"
    description: "C max"
    required: false
  c_max_unit:
    type: "str"
    description: "C max unit"
    required: false

  c_const:
    type: "str"
    description: "C constant"
    required: false
  c_const_unit:
    type: "str"
    description: "C constant unit"
    required: false

  ccat_value:
    type: "str"
    description: "C cat value"
    required: false
  ccat_unit:
    type: "str"
    description: "C cat unit"
    required: false

  ph:
    type: "str"
    description: "ph"
    required: false

  temperature:
    type: "str"
    description: "temperature"
    required: false

compare_fields: ["formula", "activity", "syngony", "surface", "length", "length_unit", "width", "width_unit", "depth", "depth_unit", "reaction_type", "km_value", "km_unit", "vmax_value", "vmax_unit", "ph", "temperature", "c_min", "c_min_unit", "c_max", "c_max_unit", "c_const", "c_const_unit", "ccat_value", "ccat_unit"]
float_tolerance: 0.05